rsmml/cashless_386

app/views/vendors/_vendor_popup.html.erb

add a half star if rating has decimal

---

app/javascript/plugins/init_mapbox.js

We have a button to find the user's coordinates.

add track my location to map

---

app/assets/stylesheets/config/_fonts.scss

- Set up new Font Family to **Montserrat** for Body and **Poppins** for Headers

set up new font family

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_rating_options.scss
app/javascript/plugins/init_star_rating.js
app/views/reviews/new.html.erb

For now it looks like this and you can merge it. I'll still keep working on it to make it look better.

Review options

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_rating_options.scss
app/assets/stylesheets/components/_ratings.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/reviews/new.html.erb

Just changed some stylings to display the form.

Styling reviews

---

app/controllers/bills_controller.rb
app/views/bills/new.html.erb

date was not stored in the Bill instance. I fixed it.

fix bills controller #new and #create methods

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search_bar.scss
app/assets/stylesheets/components/_vendor_map.scss
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/views/vendors/_search_bar.html.erb
app/views/vendors/_vendor_popup.html.erb

I put the search bar on the map.
I fixed the bug with the map directions, now it works perfectly 🚀 
did some styling on cards(still a long way to go).

Put search bar on map

---

db/migrate/20200730191556_add_user_ref_to_cards.rb
db/schema.rb

Some conflict with migrations fixed

migrations fixed

---

app/views/layouts/application.html.erb

I uncommented so the stripe checkout element works

stripe card div

---

app/controllers/dashboards_controller.rb
app/views/shared/_last_movements.html.erb
app/views/shared/_map.html.erb
config/routes.rb

map added to dashboad

---

app/assets/stylesheets/components/_last_movements.scss
app/javascript/components/historial-menu.js
app/views/shared/_last_movements.html.erb

Map card now goes Up and Down
https://recordit.co/Ryd4LVKCgC

map-card in dashboard now gows up and down

---

config/environments/production.rb

production.rb changed

---

app/controllers/dashboards_controller.rb
app/views/shared/_last_movements.html.erb
app/views/vendors/_map.html.erb

Only partial fixes. 
There is more work to be done.

partial fix

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_user_last_movements.scss
app/views/shared/_last_movements.html.erb
app/views/shared/_user_last_mov.html.erb
db/migrate/20200804120011_change_historial_amount_integer_for_float.rb
db/schema.rb

I add style to the Historial Card on Dashboard

Last_movs card with style

---

app/controllers/vendors_controller.rb
app/javascript/components/options-menu.js
app/views/shared/_display_menu.html.erb
app/views/vendors/index.html.erb

Still miss some stile but now the map is on the Options-Menu
https://recordit.co/aKvWdOm8Kq

Adding map btn

---

app/javascript/components/qr-reader.js
app/javascript/packs/application.js
app/javascript/plugins/fill_card_details.js
app/javascript/plugins/init_mapbox.js

I put the name of the vendors when you zoom in the map, so that they are not on top of each other at low zooms, but we can see the name of the stores. 
I also commented out the QR_reader JS. Please put it back in when you work on it again.

map markers display name of place on zoom

---

app/controllers/dashboards_controller.rb
app/views/dashboards/_map_popup.html.erb
app/views/dashboards/show.html.erb
app/views/shared/_last_movements.html.erb

I took out the map from the dashboard.

map deleted from DashBoard

---

app/javascript/packs/application.js
app/views/dashboards/camera.html.erb
app/views/layouts/application.html.erb

Fixing Heroku camera.
I moved the JS of the Qr Reader to the bottom of the body.

JS tranfered to the bottom of the body

---

app/javascript/components/historial-menu.js
config/application.yml

Historial menu now goes up till 70 vh

fix up to 75 vh

---

app/controllers/reviews_controller.rb

I fixed the redirect_to action when the review is saved.
https://recordit.co/WW8r4IJRu9

Review path

---

app/views/vendors/_vendor_popup.html.erb

I comment out the Stars rating from the map to try if heroku works.

stars rating commented out

---

app/views/dashboards/camera.html.erb

changed camera size when scaning qr code

changed video size

---

db/migrate/20200806170323_change_colum_name_from_cards.rb
db/schema.rb

Table CARDS, type column changed to card_type column

change column type to Card_type on Table Cards

---

app/javascript/plugins/init_mapbox.js

geolocation on

---

db/migrate/20200806170323_change_colum_name_from_cards.rb
db/migrate/20200807214921_add_data_to_users.rb
db/schema.rb

add stripe_id column to users table, to keep the customer id of stripe.

add stripe_id to users

---

app/controllers/payments_controller.rb

another measure against X-CSRF-Token

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_map.scss
app/views/vendors/_search_bar.html.erb
app/views/vendors/index.html.erb

styling map

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/dashboards/show.html.erb
app/views/shared/_display_menu.html.erb
app/views/shared/_last_movements.html.erb

-changed "add new card" icon
-changed content for "Transactions" "My QR code" "Map"
-changed color of icons for the side menu to white

changed some styles and content

---

app/assets/stylesheets/components/_vendor_map.scss
app/javascript/plugins/init_mapbox.js
app/views/vendors/index.html.erb

The map no longer displays popups, but puts the info on the vendor in the container from bottom of page

Put popup info in container

---

app/javascript/packs/option-slider.js
app/views/dashboards/show.html.erb
app/views/layouts/application.html.erb

Js Refractor from slide option menu

refractor js

---

app/controllers/payments_controller.rb
app/views/bills/show.html.erb
db/migrate/20200810163918_remove_checkout_session_from_bills.rb
db/migrate/20200810164208_add_charge_to_bills.rb
db/schema.rb

I added a charge column (id) in the bills_table.
Through charge (id),  we can get payment information from Stripe and link the payment status with sweetalert, which shows "success" regardless of the status now.
[`Stripe::Charge.retrieve(@bill.charge)`](https://stripe.com/docs/api/charges/object)
to get details of payment info such as amount, currency, name, vendor etc.
`Stripe:Charge.list({limit: 3})` 
to get 3 recent transactions of the user (stripe account owner)

Add charge column to bills_table

---

app/assets/stylesheets/components/_display_menu.scss
app/views/shared/_display_menu.html.erb

Side menu design

---

app/assets/stylesheets/pages/_map.scss
app/javascript/components/historial-menu.js
app/javascript/packs/map-description.js
app/views/vendors/_vendor_popup.html.erb
app/views/vendors/index.html.erb

I add style to the Vendors Card on the Map.
https://recordit.co/AWasyI0Sp9

Style map card

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_sign-in.scss
app/views/devise/sessions/new.html.erb

Just a better log-in page. nothing special.

sign-in page design

---

app/assets/stylesheets/components/_modal_review.scss
app/assets/stylesheets/components/_ratings.scss
app/assets/stylesheets/components/_slide_menu.scss
app/assets/stylesheets/components/_swipe-btn.scss
app/assets/stylesheets/pages/_dashboard.scss
app/views/reviews/new.html.erb

I add some style to the reviews#new page.
The Set Comments are on a grid, but somehow it does not work on my phone. I'll take a look later with the TAs

Styling review

---

app/views/vendors/_vendor_popup.html.erb

Please push to heroku to check

fix error from Heroku

---

app/assets/stylesheets/components/_bill_show_page.scss
app/controllers/payments_controller.rb
app/javascript/packs/dummy-card.js
app/views/payments/new.html.erb

- I add the Card selection in the Payments#New page
- And the btn on top-left brings you back to the camera.

dummy card on bill page

---

app/assets/stylesheets/components/_display_menu.scss
app/views/dashboards/show.html.erb

changed design of the side menu a bit. Added rounded corners

changed styling of the menu

---

app/javascript/components/tips-count.js

remove NaN when a user doesn't input tip.

Get rid of nan

---

app/javascript/packs/dummy-card.js

-Fixed active card when selecting

fixed selecting card

---

app/views/devise/sessions/new.html.erb

Log-in form with Remember me option for 1 year..

remember me on sessions new

---

app/javascript/components/plus-menu.js
app/views/shared/_plus_menu.html.erb

I've changed the +btn from dashboard to the camera with some animation:
https://recordit.co/BnGF4yEvIM

plus btn changed to camera btn on dashboard

---

app/views/shared/_display_menu.html.erb

In the side menu changed dashboard text to account

changed dashboard to account

---

app/views/reviews/new.html.erb

changed content on review

---

app/views/shared/_user_last_mov.html.erb

changed You sent to Sent

---

db/seeds.rb

changed review rating in seeds

---

app/assets/stylesheets/components/_display_menu.scss
app/javascript/components/plus-menu.js
app/views/shared/_plus_menu.html.erb

Change btn db

---

app/assets/stylesheets/components/_bill_show_page.scss

change gray

---

app/assets/stylesheets/components/_search_bar.scss
app/assets/stylesheets/pages/_map.scss
app/views/vendors/_search_bar.html.erb
app/views/vendors/index.html.erb

- I edit the Search Bar on the MAP
- I added a link to the dashboard
- The geolocation btn is on the bottom right

search bar on map styled

---

app/views/vendors/_search_bar.html.erb

changed placeholder from "Search for Cashless points" to "Search for Cashless places"

changed placeholder on map search

---

app/assets/stylesheets/components/_slide_menu.scss

I make the body overflow: hidden

overflow: hidden on body

---

app/views/shared/_user_last_mov.html.erb

if no transactions it won't break. But maybe we put a placeholder or smth

fallback if transactions is nil

---

app/javascript/packs/reviewsalert.js
app/javascript/plugins/init_review_alert.js
app/views/reviews/new.html.erb

I added an alert after letting a review:
https://recordit.co/D08jIMHElP

sweet alert after letting a review

---

app/assets/stylesheets/components/_ad.scss

moved ad text

---

app/assets/stylesheets/components/_last_movements.scss
app/assets/stylesheets/components/_user_last_movements.scss
app/views/dashboards/show.html.erb
app/views/shared/_last_movements.html.erb
app/views/shared/_user_last_mov.html.erb

- Transactions card Styled:
more right-left padding for text
less padding for amount div
EUR changed to euro sign

padding & margins on transactions card fixed

---

app/javascript/plugins/init_mapbox.js

darker style with bolder fonts streets to be visible on projector

---

app/assets/stylesheets/pages/_map.scss

Redesigned the vendors card on the map. Added some margin-bottom and deleted the border around img.

changed the design of vendors card

---

app/controllers/reviews_controller.rb
app/controllers/subscribers_controller.rb
app/javascript/packs/subscribe_alert.js
app/javascript/plugins/init_subscribe_alert.js
app/views/subscribers/new.html.erb
db/schema.rb

added sweet alert for a subscriber
[https://recordit.co/5QwqT1lgCf](https://recordit.co/5QwqT1lgCf)

Add sweetalert to subscriber

---

app/javascript/plugins/init_mapbox.js
db/seeds.rb

- Markers a bit bigger
- Directions of Vendors changed

Directions from vendors changed, marker a bit bigger
